### ISSUE TITLE
When I try node bundle.js after npm run dev and gets an error saying btoa not defined 

### ISSUE THREAD

**Issue by JoshMatthew** [olisystems/dApp-nodeJS-webpack#1]
Here is the error I am getting

webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:21
    _btoa = btoa.bind(window);
    ^

ReferenceError: btoa is not defined
    at Object.eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:21:5)
    at eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:32:30)
    at Object../app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4491:1)
    at __webpack_require__ (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)
    at eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js?:26:15)
    at Object../app/node_modules/web3/node_modules/web3-providers-ws/src/index.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4503:1)
    at __webpack_require__ (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)
    at eval (webpack:///./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js?:53:24)
    at Object../app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4141:1)
    at __webpack_require__ (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)

**Comment by m-yahya** [comment]
Hi @JoshMatthew, thanks for reporting this issue.
The issue is related to the `web3.js` library, you can read more about the issue [here](https://github.com/ethereum/web3.js/issues/1706).

Can you please try to ignore `mode_modues` using [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) and see if the issue is fixed or not.

1. Install the `webpack-node-externals` by running the command `npm install webpack-node-externals --save-dev`.
2. change the `webpack.config.js` as:

```
const nodeExternals = require('webpack-node-externals');
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const path = require('path')

module.exports = {
  target: 'node',
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
  plugins: [new CleanWebpackPlugin()],
  externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
}
```

**Comment by JoshMatthew** [comment]
I think it got worst, now even npm run dev results to error.

webpack is watching the files…

Hash: 71e894db6e8dbe1a8b25
Version: webpack 4.44.0
Time: 3125ms
Built at: 08/04/2020 2:01:52 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  2.2 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./app/src/Contract.js] 352 bytes {main} [built]
[./app/src/Metadata.js] 1.93 KiB {main} [built]
[./app/src/Methods.js] 819 bytes {main} [built]
[./app/src/Provider.js] 220 bytes {main} [built]
[./index.js] 150 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497
bytes {main} [built]
[bn.js] external "bn.js" 42 bytes {main} [built]
[buffer] external "buffer" 42 bytes {main} [built]
[child_process] external "child_process" 42 bytes {main} [built]
[crypto] external "crypto" 42 bytes {main} [built]
[crypto-browserify] external "crypto-browserify" 42 bytes {main} [built]
[os] external "os" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[randombytes] external "randombytes" 42 bytes {main} [built]
[util] external "util" 42 bytes {main} [built]
    + 372 hidden modules

WARNING in ./app/node_modules/web3/node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/Release/bufferutil' in
'C:\Users\User\Desktop\dApp-nodeJS-webpack-master\app\node_modules\web3\node_modules\websocket\lib'
 @ ./app/node_modules/web3/node_modules/websocket/lib/BufferUtil.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/WebSocketFrame.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/websocket.js
 @ ./app/node_modules/web3/node_modules/websocket/index.js
 @ ./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js
 @
./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js
 @ ./app/node_modules/web3/node_modules/web3-core/src/index.js
 @ ./app/node_modules/web3/src/index.js
 @ ./app/src/Provider.js
 @ ./app/src/Methods.js
 @ ./index.js

WARNING in ./app/node_modules/web3/node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/Release/validation' in
'C:\Users\User\Desktop\dApp-nodeJS-webpack-master\app\node_modules\web3\node_modules\websocket\lib'
 @ ./app/node_modules/web3/node_modules/websocket/lib/Validation.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/WebSocketConnection.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/websocket.js
 @ ./app/node_modules/web3/node_modules/websocket/index.js
 @ ./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js
 @
./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js
 @ ./app/node_modules/web3/node_modules/web3-core/src/index.js
 @ ./app/node_modules/web3/src/index.js
 @ ./app/src/Provider.js
 @ ./app/src/Methods.js
 @ ./index.js

WARNING in ./app/node_modules/web3/node_modules/websocket/lib/BufferUtil.js
Module not found: Error: Can't resolve '../build/default/bufferutil' in
'C:\Users\User\Desktop\dApp-nodeJS-webpack-master\app\node_modules\web3\node_modules\websocket\lib'
 @ ./app/node_modules/web3/node_modules/websocket/lib/BufferUtil.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/WebSocketFrame.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/websocket.js
 @ ./app/node_modules/web3/node_modules/websocket/index.js
 @ ./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js
 @
./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js
 @ ./app/node_modules/web3/node_modules/web3-core/src/index.js
 @ ./app/node_modules/web3/src/index.js
 @ ./app/src/Provider.js
 @ ./app/src/Methods.js
 @ ./index.js

WARNING in ./app/node_modules/web3/node_modules/websocket/lib/Validation.js
Module not found: Error: Can't resolve '../build/default/validation' in
'C:\Users\User\Desktop\dApp-nodeJS-webpack-master\app\node_modules\web3\node_modules\websocket\lib'
 @ ./app/node_modules/web3/node_modules/websocket/lib/Validation.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/WebSocketConnection.js
 @ ./app/node_modules/web3/node_modules/websocket/lib/websocket.js
 @ ./app/node_modules/web3/node_modules/websocket/index.js
 @ ./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js
 @
./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js
 @ ./app/node_modules/web3/node_modules/web3-core/src/index.js
 @ ./app/node_modules/web3/src/index.js
 @ ./app/src/Provider.js
 @ ./app/src/Methods.js
 @ ./index.js

ERROR in
./app/node_modules/web3/node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in
'C:\Users\User\Desktop\dApp-nodeJS-webpack-master\app\node_modules\web3\node_modules\swarm-js\node_modules\got'
 @ ./app/node_modules/web3/node_modules/swarm-js/node_modules/got/index.js
45:20-39
 @ ./app/node_modules/web3/node_modules/swarm-js/lib/files.js
 @ ./app/node_modules/web3/node_modules/swarm-js/lib/api-node.js
 @ ./app/node_modules/web3/node_modules/web3-bzz/src/index.js
 @ ./app/node_modules/web3/src/index.js
 @ ./app/src/Provider.js
 @ ./app/src/Methods.js
 @ ./index.js
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat
'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat
'C:\pagefile.sys'

**Comment by m-yahya** [comment]
@JoshMatthew I already reported the error [here](https://github.com/ethereum/web3.js/issues/3667#issue-671871205).
Let's keep fingers crossed.

**Comment by JoshMatthew** [comment]
Thank you!
